// lib/features/notes/domain/usecases/create_note_use_case.dart

import 'package:fpdart/fpdart.dart';
import 'package:uuid/uuid.dart';

import '../../../../core/errors/failures.dart';
import '../../../../core/usecases/use_case.dart';
import '../entities/note_entity.dart';
import '../entities/note_status.dart';
import '../repositories/note_repository.dart';

/// Input parameters for [CreateNoteUseCase].
///
/// The use case generates the [NoteEntity.id] and all timestamps —
/// the caller only provides the user-supplied content.
class CreateNoteParams {
  const CreateNoteParams({
    required this.title,
    required this.body,
    this.color,
    this.categoryId,
    this.tagIds = const [],
    this.isFavorite = false,
  });

  /// The note title. May be empty if [body] is non-empty.
  final String title;

  /// The note body. May be empty if [title] is non-empty.
  final String body;

  /// Optional background color as an ARGB integer.
  final int? color;

  /// Optional category ID (Phase 2).
  final String? categoryId;

  /// Optional list of tag IDs (Phase 2).
  final List<String> tagIds;

  /// Whether the note starts as a favorite.
  final bool isFavorite;
}

/// Creates and persists a new note.
///
/// Business rules:
///   1. [CreateNoteParams.title] and [CreateNoteParams.body] are trimmed of
///      leading/trailing whitespace before any further processing.
///   2. If BOTH trimmed title and trimmed body are empty, the note is rejected
///      with a [NoteValidationFailure] — a blank note is meaningless.
///   3. A UUID v4 is always generated by this use case. The caller never
///      supplies an ID, preventing duplicate or colliding keys.
///   4. [NoteEntity.createdAt] and [NoteEntity.updatedAt] are both set to
///      the same [DateTime.now()] captured once at call time.
///   5. New notes always start with [NoteStatus.active] and [isPinned] = false.
class CreateNoteUseCase implements UseCase<NoteEntity, CreateNoteParams> {
  const CreateNoteUseCase(this.repository);

  /// The note repository. Never references Hive directly.
  final NoteRepository repository;

  @override
  Future<Either<Failure, NoteEntity>> call(CreateNoteParams params) async {
    final title = params.title.trim();
    final body = params.body.trim();

    // Business rule 2: reject blank notes.
    if (title.isEmpty && body.isEmpty) {
      return const Left(
        NoteValidationFailure('A note must have a title or body.'),
      );
    }

    final now = DateTime.now();

    final entity = NoteEntity(
      id: const Uuid().v4(),      // Business rule 3: always generate UUID here.
      title: title,               // Business rule 1: trimmed.
      body: body,                 // Business rule 1: trimmed.
      color: params.color,
      isPinned: false,            // Business rule 5: never pinned on creation.
      isFavorite: params.isFavorite,
      status: NoteStatus.active,  // Business rule 5: always active on creation.
      createdAt: now,             // Business rule 4: same instant for both.
      updatedAt: now,
      categoryId: params.categoryId,
      tagIds: params.tagIds,
    );

    return repository.createNote(entity);
  }
}
